### ISSUE TITLE
'HV panic down' and 'All triggers off' buttons: global, big and obvious

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#10]
It should be very easy to find the HV panic-down and the all-triggers-off buttons. 
We discussed two solutions:
- Have a separate GUI that always stays on top with the two big buttons in obvious colors. This GUI can then be placed in one corner. 
- Have these buttons inside a footer in every GUI element.
  The first option is probably least confusing.

**Comment by tlatorre-uchicago** [comment]
Mostly solved by Javi's new SNO+ GUI. Should we close? @marzece found a way to make sure that this window always stays on top, so we could wait for that. Opinions?

**Comment by fbdescamps** [comment]
You mean to leave the SNO+ GUI always on top? That could be a bit cumbersome (depending on screen resolution :P). I still think it would be a good thing to have a dedicated smaller window for this. Other opinions?

**Comment by marzece** [comment]
Yeah the floating on top thing is pretty easy. I was considering either doing it to the whole SNOP GUI and having an itunes style shrink window button. Or have a button that pops up a window that floats on top and has the "danger zone" buttons. The first has the advantage of not making duplicate buttons but I'm less sure how to implement it.

**Comment by fbdescamps** [comment]
After discussion in the DAQ workshop on August 15th, I think it was decided that we would go with a dedicated  GUI that always stays on top with the two big buttons in obvious colors. This GUI can then be placed in one corner and persist over different desktops.  Volunteers?

**Comment by fbdescamps** [comment]
Noel is standing next to me and confirms that this would be nice to have.

**Comment by fbdescamps** [comment]
I am going to close this issue. If operator feedback indicates that we need an 'always-on-top' GUI element for this, we can re-open.
