### ISSUE TITLE
There are only 10 mtca threshold boxes but it sends 14 values to the mtca client

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#102]
The last 4 are all junk/initialized data I believe.

**Comment by tlatorre-uchicago** [comment]
They are now set to zero. The last four are labeled as spares, presumably in case we add MTCAs. I think this is OK for now. Do you agree?

**Comment by marzece** [comment]
Yeah. Sounds good. The odds that we ever use those spares is effectively 0.
