### ISSUE TITLE
HV controls: grey out HV controls when in physics run.

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#139]
As discussed in the DOW2016: we might want to prevent the operator from changing the HV (other than panic down) while in a physics run. Should be allowed in maintenance run.

**Comment by BenLand100** [comment]
To clarify: changing HV should only be allowed in maintenance runs or changing HV should only be disallowed in physics runs?

**Comment by fbdescamps** [comment]
My opinion is that we should only allow changed to HV in maintenance runs. We will off course allow individual crate panic downs. Other opinions/concerns anybody?

**Comment by tlatorre-uchicago** [comment]
I think we shouldn't overcomplicate the controls. Since there is already a plan to only allow changes with an expert password, we shouldn't add in more checks that require cross model communication.

**Comment by fbdescamps** [comment]
@tlatorre-uchicago @BenLand100 What is the decision on this? Please retire and replace with a better formulated issue if required.

**Comment by BenLand100** [comment]
@jcaravaca implemented non-expert locking in such a way as to handle this. My understanding is that unlocking puts you in maintenance mode, and otherwise the controls are locked. Unless I am mistaken this can be closed. (But otherwise modifications should be done to existing locking logic as tony suggests.)

**Comment by jcaravaca** [comment]
The new operator mode PR fixes this: the HV will be available only in expert mode if the run is stopped or in maintenance. I'd keep this up and include it as a HV test once Ben's and my PRs are merged.

**Comment by tlatorre-uchicago** [comment]
@jcaravaca Do you still want to leave this up?

**Comment by jcaravaca** [comment]
Do we want this to happen? If there is an emergency in the middle of a Physics run we might want to ramp down a crate. The XL3s HV controls are blocked but that's not true for the SNO+ GUI.

**Comment by fbdescamps** [comment]
This might be related to issue #221 , where it is suggested that we add 'ramp down' to the HV master. If we want to allow operators to ramp down a crate we need to either:
 * allow access to HV controls
 * add ramp down to HV master

**Comment by jcaravaca** [comment]
I would go for allowing access to the HV controls. This is not an emergency operation unlike Panic Down so it's reasonable to use the XL3 panel. The other question is that whether we really want to allow the operator to perform this task and in which situation that'd be useful.

**Comment by tlatorre-uchicago** [comment]
I think the current plan is to enable ramp down and HV off for non experts.
