### ISSUE TITLE
E-stop: implement and test action when big red mushroom button is pushed

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#14]
The following E-stop implementation needs to be in place and tested before FTB. When an operator pushes the button (to be discussed in detail):
 * There is a 5sec grace-period, where the button can still be ```unpressed``` without any consequences.
 * After 5sec, the HV is ramped down on all crates.

This can be implemented through TUBII, with the XL3server directly sending the ramp-down (non-existent at the moment) command to the XL3's.

**Comment by marzece** [comment]
Perhaps implement this as a separate server running on a raspberry-pi or something like that.

**Comment by tlatorre-uchicago** [comment]
Solved by @marzece. This is now handled by the estop-server.
