### ISSUE TITLE
XL3 Graphic to red

### ISSUE THREAD

**Issue by parnmatt** [snoplus/orca#141]
Not a huge thing, just would be nice if the XL3 in the ORCA crate looked more like an XL3, i.e., at least red.

Would be easier for operators to quickly identify the XL3.
I know I would find it much easier.

**Comment by tlatorre-uchicago** [comment]
If someone sends me a nice high quality photo of an XL3 from the front in good lighting, I will add it to ORCA.

I agree this would be nice.

**Comment by marzece** [comment]
I actually have a branch where I did this sitting around. I didn't like the new look of it so I kinda dropped it. But I can add a PR anyways and people can decide if the change is so aesthetically offensive that it will ruin orca

**Comment by marzece** [comment]
Here's the image I used if anyone else wants to try.
![xl3_image](https://cloud.githubusercontent.com/assets/4153907/17752354/6a2f9c66-6499-11e6-9caa-d8d25b520979.png)

**Comment by tlatorre-uchicago** [comment]
fixed in #144.
