### ISSUE TITLE
Init with coder and encoder for all GUIs

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#147]
Moved from old repo. Quote Chris: "Need to make sure that whenever a GUI (i.e. XL3/ELLIE/SNO+ Main Control) is closed that these are initialised with an encoder so the values are not lost....". Please close if no longer relevant. @BenLand100 @tlatorre-uchicago.

**Comment by tlatorre-uchicago** [comment]
This is generally what happens. I think most settings are indeed currently saved, but it might be worth making sure when editing any of these models.
