### ISSUE TITLE
There should be  a standard run that changes no settings at all when started.

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#180]
I think the SNO term was "diagnostic" run.

**Comment by jcaravaca** [comment]
@marzece what is the use case for this? In principle you won't be allowed to change settings in this run
since that'd be Maintenance.

**Comment by marzece** [comment]
Could there be a special version of Maintenance that won't change any settings?

**Comment by tlatorre-uchicago** [comment]
I think you should be allowed to change detector settings for this run. The idea is we need a way from the SNO+ run control to start new runs without touching the detector to debug things. I think we discussed this at the last DAQ workshop, and assigned bit 6 to this run.

**Comment by jcaravaca** [comment]
#183 includes the diagnostic run. I'm not still convinced we need both Maintenance and Diagnostic, but for the time being I added that posibility and we will learn from experience whether both are actually useful.

**Comment by tlatorre-uchicago** [comment]
Fixed in #183.
