### ISSUE TITLE
HW wizard should update the FEC PMT state GUI 

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#186]
When HW wizard does not turn on trigger because of pmthv bit in pmtdb (and we confirmed that this is indeed the case), it does not correctly update the  FEC PMT state GUI. As in:
 * channel 0/4/25 has a pulled resistor
 * we use the HW wizard to turn n100 on.
 * it does not actually do it since it knows that the resistor is pulled.
 * in the FEC PMT GUI state it claims n100 is on. 

@boardhead

**Comment by tlatorre-uchicago** [comment]
I'm not able to reproduce this on the teststand.
