### ISSUE TITLE
XL3 status shows "label" if you don't check it

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#195]
Screenshot attached
<img width="654" alt="screen shot 2016-12-08 at 8 18 51 pm" src="https://cloud.githubusercontent.com/assets/4153907/21034166/94af1da2-bd83-11e6-9890-4eefc6557af5.png">

**Comment by fbdescamps** [comment]
@jcaravaca

**Comment by tlatorre-uchicago** [comment]
Fixed in #367.
