### ISSUE TITLE
Can't do charge injection while monitoring base currents

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#220]
It seems monitoring base currents while doing charge injection will cause charge injection to stop. This might be a hardware limitation and not an orca problem though.

**Comment by tlatorre-uchicago** [comment]
@marzece confirmed that this is a hardware limitation.

**Comment by marzece** [comment]
To be precise the ML403 code could be changed to solve this if we ever wanted to in the future. So it's not strictly a hardware issue, but regardless it's not an orca issue.
