### ISSUE TITLE
HV Ramp Down button on Control Panel

### ISSUE THREAD

**Issue by ecaden** [snoplus/orca#221]
There should be a "ramp down" button on the HV master for each crate, for a normal user to ramp down a crate in a controlled, non-panic situation. Ramping a crate should still be an expert operation.

**Comment by jcaravaca** [comment]
What is the use case of an operator ramping down a crate? If it is not a emergency situation, would make more sense to use the XL3 panel?

**Comment by tlatorre-uchicago** [comment]
I agree this should be done from the XL3 panel so we don't duplicate a bunch of buttons.

**Comment by tlatorre-uchicago** [comment]
I'm going to close this. I think the current plan is to enable the operator to ramp down from the XL3 GUI.
