### ISSUE TITLE
If you hit ramp up while still editing the target field the ramp goes to the previous entered target 

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#226]
This might be intended behaviour but if you have the target set to (say) 2kV then change that to 200V then without hitting enter, you click ramp up, then the crate will ramp to 2kV. It might be better to have the ramp up button end the editing of the target field and use the value currently in there. Or just refuse to do any ramping if that field is still being edited.

**Comment by fbdescamps** [comment]
@BenLand100

**Comment by tlatorre-uchicago** [comment]
Fixed in #271.
