### ISSUE TITLE
SNO+ control panel: Run Type word protection

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#227]
The operator can change any radio-button state in the SNO+ main GUI run-type word. The only ones that an operator should be allowed to change is the bottom set of 'detector state' .  The other bits should be set depending on which run is selected.

Also, the spare bits should be greyed out and not selectable.

**Comment by fbdescamps** [comment]
@jcaravaca

**Comment by tlatorre-uchicago** [comment]
Fixed in #234.
