### ISSUE TITLE
Channel Sequencer state logic in ORCA

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#229]
I just want to add this here to further discuss how/if we want to change the way ORCA deals with channels that have sequencers off/on. Currently, even if a crate is on LV, ORCA will turn the sequencer on for any channel that it things has HV by looking at the relay mask.

The ideal case:
 * we have a list somewhere of 'bad' channels for which the sequencer should be off due to discovered/known issues.
 * we know, by looking at the relay mask and the pmtdb (pulled_r, etc), which channels have a PMT on HV

Then, at the start of each run:
   * if there is a PMT on HV and no known sequencer issue: turn/leave sequencer on even if the operator has turned it off and warn operator is sequencer state was changed.
   * if there is a PMT on HV but a known sequencer issue: turn/leave sequencer off but throw alarm. In this case, we should have the relay open until we can fix the channel?
   * if a channel is on LV and no known sequencer issue: leave sequencer state as is.
   * if channel is on LB and known sequencer issue: turn/leave sequencer off and warn operator if sequencer state was changed.

Ideas/corrections? How will we get to this state? What are the intermediate steps?

**Comment by fbdescamps** [comment]
@tlatorre-uchicago @boardhead What is the plan here? I think the next important step is to add the pmtdb info (pmthv: is the resistor pulled or not?) logic to this at run-start? Thanks!

**Comment by tlatorre-uchicago** [comment]
This is largely solved by the channel database.
