### ISSUE TITLE
Change colors of trigger thresholds in Standard Run tab for colorblind users

### ISSUE THREAD

**Issue by jackdunger** [snoplus/orca#230]
At @ecaden's request. They are currently red/green, red/blue like the rest of the GUI could be safer.

**Comment by tlatorre-uchicago** [comment]
I would vote for bold and grey for enable/disabled.

**Comment by jcaravaca** [comment]
We've used red/blue throughout ORCA and it'd be nice to be consistent, but I can change it if some other people chime on this

**Comment by tlatorre-uchicago** [comment]
Fixed in #234.
