### ISSUE TITLE
FEC Pedestal mask not displayed

### ISSUE THREAD

**Issue by jcaravaca** [snoplus/orca#24]
I'd be nice to have a display of the current pedestal mask in a FEC by FEC basis

**Comment by fbdescamps** [comment]
@jcaravaca, what is the status here? Any plan to move forward?

**Comment by jcaravaca** [comment]
This is something that might be retrieved from the detector state and could be displayed at the Minard crate views. Not critical though, just a nice to have.

**Comment by fbdescamps** [comment]
Ok, I will remove this from the ORCA issues and add it to Minard.
