### ISSUE TITLE
ECA data taking slows down when Run Controls on top

### ISSUE THREAD

**Issue by jcaravaca** [snoplus/orca#240]
ECA runs take a factor of ~2 longer when both Run Controls are visible on display. When covered or minimized, ECA runs speed up.

**Comment by jcaravaca** [comment]
According to Mark Howe the Orca-scripts (used by the ECAs) run in the main thread and then, any GUI update holds the script normal flow.

**Comment by tlatorre-uchicago** [comment]
@jcaravaca you mentioned a while ago that you were going to move the ECA runs from scripts to a separate thread. Is that still the plan?

**Comment by jcaravaca** [comment]
Yes, I've mentioned that at today's call. However, this is not at the top of my priority list so it might take some time. This doesn't prevent to get ECA runs in any case.

**Comment by jcaravaca** [comment]
Fixed in #255
