### ISSUE TITLE
Hardware wizard not properly setting channel triggers to off for open paddle cards

### ISSUE THREAD

**Issue by tannerbk** [snoplus/orca#246]
If you try to turn on channel triggers for an entire crate using the hardware wizard, it should prevent you from turning them on for channels with a pulled resistor and channels with an open paddle card.

It seems to work for pulled resistors but not open paddle cards. I think @tlatorre-uchicago is already aware.

**Comment by tlatorre-uchicago** [comment]
Fixed in #256.
