### ISSUE TITLE
ORCA crate-view lock in non-obvious location

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#247]
We noticed this when trying to delete a FEC card from crate 11. There was a blue line that read 'Document is locked' under the crate-graphics, but the window itself does not have a lock. To unlock, one needs to go to the lock in the bottom left corner of the experiment-window. It would be nice to have a lock available in the crate-view window itself.

**Comment by tlatorre-uchicago** [comment]
I don't think this is possible. My guess is that the code which prevents you from deleting a card when the document is locked is in the ORCA object code. If we were to place a lock here, it would then have to enable unlocking the entire experiment, i.e. there is no way to just unlock it for just the crate view and not the VME crate view.
