### ISSUE TITLE
unable to unlock the SNO+ control panel

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#250]
Currently on operug1, it is impossible to unlock the SNO+ control panel. When you click on the lock, the computer beeps but no dialog appears.

I verified that the lock works in the FEC GUI, so it appears to be just that window.

**Comment by tlatorre-uchicago** [comment]
I can't seem to reproduce this after closing and opening the SNO+ control window, so I'm not sure what caused the problem.

**Comment by jcaravaca** [comment]
Could that be related with the fact that the panel was frozen?

**Comment by tlatorre-uchicago** [comment]
No, the rest of the GUI was responsive.

**Comment by jcaravaca** [comment]
@tlatorre-uchicago have you seen this again recently? I didn't hear about anyone complaining about this nor see this behavior myself, so I'll close the issue for now.
