### ISSUE TITLE
DB values not showing up in the SNO+ control panel

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#251]
I was in a MAINTENANCE run, then selected PHYSICS run from the drop down list and hit overwrite standard run.

After this, the DB values column shows nothing for PHYSICS and MAINTENANCE runs, but still shows OK for all the other runs.

<img width="1284" alt="screen shot 2017-01-18 at 3 38 59 pm" src="https://cloud.githubusercontent.com/assets/5834059/22082100/62600448-dd94-11e6-8273-4fc8ffd0b023.png">

Here is the relevant messages from the Orca log:

```
17-01-18 15:00:26 Unversioned directory17-01-18 15:00:26 /Users/snoperator/Desktop/Orca.app/Contents/Resources/svnversion17-01-18 15:00:26 ---------------------------------------
17-01-18 15:00:26 Run 12636 started(cold start).
17-01-18 15:00:26 DataTaking Thread Started
17-01-18 15:22:24 Loading settings for standard run: MAINTENANCE - Version: DEFAULT ........ 
17-01-18 15:22:24 DataTaking Thread Exited
17-01-18 15:22:25 Transfer queue cleared successfully
17-01-18 15:22:25 Waiting for transfer thread to exit
17-01-18 15:22:25 Transfer thread exited
17-01-18 15:22:25 Final end of run cleanup
17-01-18 15:22:25 Run 12636 stopped.
17-01-18 15:22:25 Disabled Pedestals.
17-01-18 15:22:25 Enabled Pulser.
17-01-18 15:22:25 Set GT Coarse Delay to 0xf0
17-01-18 15:22:25 Set GT Fine Delay to 0x00
17-01-18 15:22:25 mtc: pulser rate set to 10.00 Hz
17-01-18 15:22:25 Set Ped Mask: 0x01ffffff
17-01-18 15:22:25 Set GT Crate Mask: 0x01ffffff
17-01-18 15:22:25 Cleared GT Mask
17-01-18 15:22:25 Successfully loaded MTCA+ thresholds
17-01-18 15:22:25 MTCA: set N100 crate mask to 0x0007f67c
17-01-18 15:22:26 MTCA: set N20 crate mask to 0x0007f67c
17-01-18 15:22:26 MTCA: set EHI crate mask to 0x0007ffbf
17-01-18 15:22:26 MTCA: set ELO crate mask to 0x000fdfff
17-01-18 15:22:26 MTCA: set OELO crate mask to 0x00000008
17-01-18 15:22:26 MTCA: set OEHI crate mask to 0x00000008
17-01-18 15:22:26 MTCA: set OWLN crate mask to 0x00000008
17-01-18 15:22:26 Set GT Mask: 0x02006649
17-01-18 15:22:29 Passed Configuration Checks
17-01-18 15:22:29 ----------------------------------------------------------
17-01-18 15:22:29 Warning: Run Started with empty readout list.
17-01-18 15:22:29 ----------------------------------------------------------
17-01-18 15:22:29 Unversioned directory17-01-18 15:22:29 /Users/snoperator/Desktop/Orca.app/Contents/Resources/svnversion17-01-18 15:22:29 ---------------------------------------
17-01-18 15:22:29 Run 12637 started(cold start).
17-01-18 15:22:29 DataTaking Thread Started
17-01-18 15:33:47 Saving settings for Standard Run: PHYSICS - Version: DEFAULT ........ 
17-01-18 15:33:47 PHYSICS run saved as standard run. 
17-01-18 15:33:47 CouchDB
17-01-18 15:33:47 rev : 1-dbb1cd2d102fdc3acedb0e03ba61209e
17-01-18 15:33:47 ok : 1
17-01-18 15:33:47 id : 2c87d4a634c0685f1a16f1682cf8baa0
```

This issue persists after refreshing the standard runs.

**Comment by tlatorre-uchicago** [comment]
I think this was caused by these standard runs having the diagnostic bit set in the run type word. Not sure how that happened, as I was definitely in a MAINTENANCE run before selecting PHYSICS run from the drop down menu. Perhaps last night shifters accidentally saved a maintenance run with the diagnostic bit set?

I think in the future we should not allow the operator to change the run type word for standard runs.

**Comment by tlatorre-uchicago** [comment]
Maybe related to #253.

**Comment by jcaravaca** [comment]
That'd be my guess: if the diagnostic bit is enabled the DB values are not shown. I see no errors in the log so that's the only explanation. Currently only experts can change the Run Type Word. This is because otherwise there is no way to properly set it, unless we change it directly in the DB. When creating or overwriting SR, the expert should follow a strict check list so that this does not happen. That'll be included in the detector manual.
