### ISSUE TITLE
Multiple SNO+ control panels

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#253]
Right now on operug1 there appear to be multiple SNO+ control panel windows.

<img width="3200" alt="screen shot 2017-01-18 at 5 18 11 pm" src="https://cloud.githubusercontent.com/assets/5834059/22085470/3d2d1694-dda2-11e6-9be0-28c886162e5b.png">

This is a problem because they also seem to be inconsistent so it's not obvious which one actually corresponds to the SNO+ model.

**Comment by jcaravaca** [comment]
Any recipe to reproduce this? I have never seen this behavior before

**Comment by tlatorre-uchicago** [comment]
No, I just saw it when I took over during the crossover shift.

**Comment by tlatorre-uchicago** [comment]
As @jcaravaca pointed out, someone probably pressed Command-C to make two windows. The fact that one was inconsistent was probably just #73.
