### ISSUE TITLE
HV control buttons flicker on when unlocking

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#269]
When you unlock the XL3 window on the HV tab *all* the buttons temporarily unlock themselves sometimes for up to a second before the ones that shouldn't be active are disabled.

**Comment by jcaravaca** [comment]
I think this is caused by a bad logic in the implementation of the security since the locking status depend also on the HV status. I noticed that while working on #262 and hopefully it's fixed there.

**Comment by tlatorre-uchicago** [comment]
Fixed in #262.
