### ISSUE TITLE
HW wizard disabled triggers for normal PMTs

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#279]
We used the HW wizard to enable triggers on shift, and it disabled the following triggers for channels which were normal PMTs which had good CMOS rates:

- [ ] 14/15/31
- [ ] 15/15 PC3
- [ ] 10/15 PC3

This could be a database problem.

**Comment by tlatorre-uchicago** [comment]
Confirmed that this is a database problem. @fbdescamps Any idea why these show up in the pmtdb table as not having HV on, but they look fine in Noel's database?

**Comment by fbdescamps** [comment]
Yeah, I need to update the table to have the correct definition for when there is no pmt attached to the channel. I'll update a comment here when that is done.
