### ISSUE TITLE
CTRL-C on any window makes a copy of it

### ISSUE THREAD

**Issue by jcaravaca** [snoplus/orca#291]
Probably related with #253
![image](https://cloud.githubusercontent.com/assets/10038219/22492926/5529d1b2-e7e1-11e6-8e2c-641deac88dd9.png)

**Comment by BenLand100** [comment]
Note that on the site machines we see this with Command-C (Clover-C) but not CTRL-C

**Comment by tlatorre-uchicago** [comment]
Ah, I had forgotten about this. Mark Howe had mentioned this a while ago as one of the reasons for having the model store all the state and not having the controller store anything. I think I forwarded that email around to the DAQ group. I just tested this and the two SNO+ control panels appear to be consistent (i.e. they both update when things change).
