### ISSUE TITLE
When using postgres object in nearly empty experiment it grabs a bunch of data still

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#298]
<img width="915" alt="screen shot 2017-02-03 at 4 36 06 pm" src="https://cloud.githubusercontent.com/assets/4153907/22610208/5bf957e4-ea32-11e6-8784-b81e61c10de2.png">

Screenshot attach. I got warning about triggers being on and stuff even though I had no FECs or anything in the experiment.

**Comment by boardhead** [comment]
Right.  The PostgreSQL model loads the complete detector configuration and issues warnings based on that, not based on the current ORCA configuration.
