### ISSUE TITLE
Add 'keep alive' pulse for TUBii

### ISSUE THREAD

**Issue by EdLeming** [snoplus/orca#334]
As it stands, if ORCA dies, TUBii will continue to issue triggers (for example to TELLIE). As a result, TELLIE will keep firing while we have no detector control. 

We should add a safety measure to ensure this can't happen. The proposal is to add a keep alive pulse from ORCA to the TUBii server. If TUBii misses a keep alive ping (i.e. ORCA has died) TUBii stops issuing triggers.

**Comment by fbdescamps** [comment]
@EdLeming has this been resolved and merged? Thanks!

**Comment by EdLeming** [comment]
PR #359 waiting for final approval

**Comment by tlatorre-uchicago** [comment]
Added in #359.
