### ISSUE TITLE
can't close Orca

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#335]
Currently, it's not possible to quit Orca during a run by going to Orca -> Quit Orca. I suspect this is due to exceptions being thrown when objects are deallocated, but I'm not 100% sure. This needs to be fixed because it is part of the handover procedure.

Here are a couple of segfaults I've seen when trying to quit Orca while a run is going on:

- [ ] ORDataTaskModel
- [ ] XL3 HV Thread

**Comment by tlatorre-uchicago** [comment]
Here are a couple of segfaults I have seen on the teststand when trying to quit while a run is going on:

![screen shot 2017-03-04 at 7 36 59 pm](https://cloud.githubusercontent.com/assets/5834059/23583426/2acfcc74-0112-11e7-9061-d84f2fbd3f17.png)
![screen shot 2017-03-04 at 7 38 35 pm](https://cloud.githubusercontent.com/assets/5834059/23583428/2d5bfbd4-0112-11e7-8138-058d95ca3d94.png)

**Comment by tlatorre-uchicago** [comment]
I was able to get Orca to quit while a run was going by calling `[runControl setRunningState:eRunStopped]` when a `OROrcaAboutToQuitNotice` notification is posted.

**Comment by fbdescamps** [comment]
@boardhead do you have an update on this issue? Thanks!

**Comment by tlatorre-uchicago** [comment]
Fixed in https://github.com/snoplus/orca/commit/49ff707c4caf73462da22465f8e9bf1bca70501f.
