### ISSUE TITLE
"Triggers ON" should be grayed out during a physics run

### ISSUE THREAD

**Issue by pershint** [snoplus/orca#340]
After forgetting to turn triggers on for crate 16 after ramping, triggers were turned on during a physics run.  I was informed that we should go to maintenance mode before turning triggers back on for a crate.

We could gray out "triggers ON" during a physics run.  This way, the operator would be required to make the move to maintenance mode before turning more triggers on.

**Comment by tlatorre-uchicago** [comment]
Fixed in #367.
