### ISSUE TITLE
Panic down all sends commands to crates serially

### ISSUE THREAD

**Issue by bonventre** [snoplus/orca#346]

**Comment by bonventre** [comment]
Orca also crashes

**Comment by bonventre** [comment]
HV appears to be on (but set to 0) for majority of crates

**Comment by tlatorre-uchicago** [comment]
Did you happen to get any errors from OSX about the crash?

**Comment by bonventre** [comment]
[orca_log.txt](https://github.com/snoplus/orca/files/838499/orca_log.txt)

**Comment by BenLand100** [comment]
It's a known `feature` on the ml403 side that the panic down packet handler doesn't turn off the supplies. I believe @marzece said this was an easy fix but it hasn't be a high priority.

**Comment by tlatorre-uchicago** [comment]
Fixed in #347.
