### ISSUE TITLE
crate 18 set HV ON after reset

### ISSUE THREAD

**Issue by tannerbk** [snoplus/orca#355]
after resetting create 18, HV comes on automatically.

**Comment by tannerbk** [comment]
Now that we've seen this a couple times, I doubt this is an Orca bug. Also, I can't remember making this issue, @jcaravaca are you satisfied to close for now (we will leave the electronic issue open).

**Comment by jcaravaca** [comment]
Sure, if we determined that it's not an ORCA issue I'm fine closing this.
