### ISSUE TITLE
ORCA started a run automatically after it's opened

### ISSUE THREAD

**Issue by jcaravaca** [snoplus/orca#360]
I saved the .ORCA file, closed ORCA, opened ORCA UG and it automatically started a new Maintenance run

**Comment by tlatorre-uchicago** [comment]
Was there a run going on when it was closed above ground? Are you sure it actually *started* a run and didn't just display that a run was already going on?

**Comment by jcaravaca** [comment]
Yeah, probably that's what happened. Didn't see that again, so I'll close this.
