### ISSUE TITLE
run document

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#37]
When submitting the run document, the function _runDocumentWorker will throw an unhandled exception if there is a FEC without a daughter board.

**Comment by tlatorre-uchicago** [comment]
In fact, it throws unhandled exceptions all over the place, for example if the MTC server can't be contacted. Maybe best to put a giant try catch block?

**Comment by fbdescamps** [comment]
Do we still need to fix this in fact?  @tlatorre-uchicago

**Comment by tlatorre-uchicago** [comment]
This function will be obsolete once we remove orcadb from the CouchDB database, so it's probably not worth spending time on assuming we get that done before water fill.

**Comment by tlatorre-uchicago** [comment]
This function has been deleted in #209.
