### ISSUE TITLE
HV Master

### ISSUE THREAD

**Issue by bonventre** [snoplus/orca#374]
HV master window does not update XL3 state automatically. It would be much more useful if it updated automatically when hardware changes.

**Comment by fbdescamps** [comment]
@BenLand100 , I remember discussing this on a call I think. How hard would this be to implement?

**Comment by BenLand100** [comment]
That's probably more of a @jcaravaca question, but I'm not sure ORCA actively queries the XL3 state... If it is, the HV master must not be listening for a notification in which case the solution would be to do that.

**Comment by tlatorre-uchicago** [comment]
Fixed in #367.
