### ISSUE TITLE
EsumHi and EsumLo labels are swapped in the MTC Gui

### ISSUE THREAD

**Issue by jcaravaca** [snoplus/orca#38]

**Comment by tlatorre-uchicago** [comment]
Where are they switched? Just in the GT mask?

**Comment by jcaravaca** [comment]
The actual labels in the GUI are switched according to the definition in the mtcDataBase.
I.e. EsumLo should be on the top and EsumHi right after this.

**Comment by tlatorre-uchicago** [comment]
I'm still confused about this. What do you mean according to the definition in the mtcDataBase? Can you point me to some source code. According to the trigger document page 70, these are correct.

**Comment by jcaravaca** [comment]
In mtcDataBase the ESumLow is right before the ESumHi:
https://github.com/snoplus/orca/blob/master/Source/Objects/Custom%20Hardware/SNO%2B/MTC/ORMTCModel.m#L143
But in the GUI the labels themselves are swapped: the ESumHi is before the ESumLow. As the mtcDataBase is filled following the order of that table, there is no consistency. If that makes sense now I can correct it in 2 secs.

**Comment by tlatorre-uchicago** [comment]
So, you are talking about the MTCA thresholds? I thought you were talking about the GT mask.

**Comment by jcaravaca** [comment]
Yeah, I meant the threshold values under the 'settings' tab.

**Comment by tlatorre-uchicago** [comment]
Ah OK. Yeah, please submit a pull request!

**Comment by tlatorre-uchicago** [comment]
Fixed by #58.
