### ISSUE TITLE
SNOP GUI's global "Triggers Off" might have turned cmos rate polling off

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#385]
I had had cmos rate polling on for every crate and I noticed that at some point that had gotten turned off. The only operation I'd done recently was turn triggers off for the entire detector so I suspect that's what caused the issue. I didn't test it though so I can't be sure.

**Comment by tlatorre-uchicago** [comment]
It does indeed do that. See here: https://github.com/snoplus/orca/blob/99bc491c1a7467c00ef4b5d00bdb3515c20ecfaf/Source/Experiments/SNOP/SNOPModel.m#L1761. No idea why this was implemented like this.

**Comment by jcaravaca** [comment]
Panic down turns polling OFF in the first place (as in the XL3 model) and the triggers OFF button inherited the same behavior. Probably not needed.

**Comment by tlatorre-uchicago** [comment]
Fixed in #406.
