### ISSUE TITLE
New ORCA when transferring control has incorrect trigger thresholds

### ISSUE THREAD

**Issue by estherturner** [snoplus/orca#413]
On 29/05, both the morning and the afternoon shift noticed that, when transferring control of the detector,  the newly opened ORCA has slightly different trigger thresholds than the database values (like closer to 16 for the N20 rather than 18.2).

**Comment by tlatorre-uchicago** [comment]
This is most likely the result of the bug here: https://github.com/snoplus/minard/issues/69.
