### ISSUE TITLE
HV master shows Trigger Status as OFF on all crates after AG->UG handover

### ISSUE THREAD

**Issue by vfischer** [snoplus/orca#419]
Triggers are ON on the Detector State page
All the trigger masks are on on the MTC and the trigger relays are closed. Seems to be only an issue in HV master.
![triggersoffhvmaster](https://user-images.githubusercontent.com/21083819/26877120-e2861c4a-4b56-11e7-92b8-0a99d444d154.png)

**Comment by tlatorre-uchicago** [comment]
Tracked this down to someone having saved the Orca file on surface on the desktop.
