### ISSUE TITLE
tubii pgt mask error in debugger

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#430]
When running Orca in XCode on operag1 which is running OSX 10.10.5, I got an error in the debugger (the window on the bottom right of XCode) just after starting Orca about not being able to connect to the tubii pgt mask button. I'm unable to reproduce on the teststand. I'll try and grab a screenshot next time.

@icoulter, if you happen to have a mac running 10.10.5, could you try and reproduce this?

**Comment by icoulter** [comment]
My mac does happen to be running 10.10.5. I don't find any issue though.
A screenshot would help.

**Comment by tlatorre-uchicago** [comment]
![screen shot 2017-05-09 at 1 06 05 pm](https://user-images.githubusercontent.com/5834059/27646259-c6c5c346-5bed-11e7-9e1d-433b477d05ce.png)

**Comment by tlatorre-uchicago** [comment]
This happened only after I clicked on the TUBii icon.

**Comment by icoulter** [comment]
Yeah. I see it now. Will try to fix it.

**Comment by icoulter** [comment]
See #431 
I'd linked the second button to the controller, changing the name of the first in the process from button->start and hadn't tidied up after myself.

**Comment by tlatorre-uchicago** [comment]
Fixed in #431.
