### ISSUE TITLE
Remote CR heartbeat

### ISSUE THREAD

**Issue by mastbaum** [snoplus/orca#466]
While controlling SNO+, Orca should post a heartbeat to some database/object store as close as possible to the detector/DAQ servers, so that the servers "know" that an operator is in control and can automatically ramp down/shut down after a timeout. The Orca functionality, as well as the detector-side database and shutdown service, require development.

**Comment by tlatorre-uchicago** [comment]
This is solved by using the database lock that Orca already acquires when it starts up.
