### ISSUE TITLE
Changing run in run type drop down while run is starting results in inconsitent run info

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#484]
I was attempting to change the standard run values by switching into a physics run then quickly changing to a diagnostic run.  While ORCA was changin runs and the stoplight graphic was at yellow,  I changed the run selection drop down to select diagnostic. When the run actually started orca claimed the run type was diagnostic. But the run type word in the database for the run was physics. I was also able to change detector settings because orca though it was in a diagnostic run.

**Comment by mastbaum** [comment]
Closed by #485
