### ISSUE TITLE
nhit monitor should tell operator to check nearline results

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#517]
Since the MTC/A+ N100 replacement, the N20 triggers show up too late to make it into the MTC/D word and so only show up in the trigger word as a MISS. This leads the nhit monitor to report that the thresholds for the N20 are >50 nhit.

One possible solution to this is to add some output in the Orca log telling the shifter to check the monitoring page for the nearline results.

**Comment by tannerbk** [comment]
#522
