### ISSUE TITLE
orca message missing newlines

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#525]
It looks like the new message about the nhit monitor is missing newlines.

<img width="723" alt="screen shot 2019-02-04 at 2 37 04 am" src="https://user-images.githubusercontent.com/5834059/52195405-c9706c80-2825-11e9-9e95-8d3975936e07.png">

**Comment by boardhead** [comment]
Fixed in version 1.1.2 34d00d04d36dc82660e3e0fa8ac2f14beb24e818
