### ISSUE TITLE
Flipping HV on/off state in SNO+ control GUI

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#68]
When starting ORCA and  turning on HV on a single crate, we noticed that the ```PMTs HV is ON/OFF``` button was flipping (on off on off on off, etc).

**Comment by jcaravaca** [comment]
Is that the global control button? Was only that or the PANIC DOWN being grayed out as well?

**Comment by fbdescamps** [comment]
Both were in flipping state, I think it was like this:
 * HV ON was combined with enabled panic down
 * HV OFF was combined with disabled panic down

But the HV was ON.

**Comment by fbdescamps** [comment]
![hvflipping 001](https://cloud.githubusercontent.com/assets/1840217/15002684/938f3f38-1158-11e6-8b9a-1075063f69e9.png)

**Comment by jcaravaca** [comment]
Does the HVMaster panel look like normal? Indicates ON/OFF the correct crates?

**Comment by fbdescamps** [comment]
Ah, we did not check this. Also, for some unknown reason, the flipping stopped and it went to ```HV ON`` when it indeed was.

**Comment by tlatorre-uchicago** [comment]
It's flipping again, and the HV master tab is stable with just crate 6
showing HV ON.

**Comment by BenLand100** [comment]
https://github.com/snoplus/orca/blob/master/Source/Experiments/SNOP/SNOPController.m#L460
In the event that there is a value in ```aNote``` the ```globalHVON``` variable is not set as an OR of XL3 states. This notification is shipped with a value for ```aNote``` for each connected XL3 so ```globalHVON``` should be set by looping over the XL3s outside that ```if``` statement and all will be good.
