### ISSUE TITLE
SNO+ GUI is not in sync with run control

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/orca#72]
At some point during the running, the SNO+ GUI run control was no longer in sync with the run control.
![screen shot 2016-05-03 at 10 08 38 pm](https://cloud.githubusercontent.com/assets/5834059/15003667/38d609b8-117c-11e6-96f6-19dc530af951.png)

**Comment by jcaravaca** [comment]
This is the same as #73

**Comment by jcaravaca** [comment]
Fixed in #75

**Comment by jcaravaca** [comment]
Closing because it is not really a syncing problem but that the panel freezes (same that #73 )

**Comment by jcaravaca** [comment]
@tlatorre-uchicago is it really out of sync or just frozen?

**Comment by tlatorre-uchicago** [comment]
I think it was just frozen. Closing and reopening the window brought it back in sync.

**Comment by tlatorre-uchicago** [comment]
Same as #73. Closing again.
