### ISSUE TITLE
HV control improvements

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#8]
When a ramp-up is initiated for a crate, stop ramping up when the read-back current exceeds a threshold (TBD). This might be a GUI input?

**Comment by BenLand100** [comment]
Tacking onto this issue: continuously (every minute) poll HV I and V
- [ ] Prompt operator on over current
  * Better to simply ramp down?
- [ ] Prompt operator if V or I drops to 0 -> setpoint to 0 and supply off
  * Cases: supply tripped, hv kill switch, misc failure

**Comment by tlatorre-uchicago** [comment]
Fixed by #46.
