### ISSUE TITLE
Standard run selection is not saved to .orca

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#81]
When crashing ORCA, it comes back as ```ECA``` and ```ped``` version. The orca state was saved right before crashing ORCA. The way we crashed ORCA is to just ```kill -9``` the process.

**Comment by jcaravaca** [comment]
Fixed in #75

**Comment by fbdescamps** [comment]
Since this is fixed in #75 and that one is merged, I am going to close this issue. @jcaravaca
