### ISSUE TITLE
Asking about keychains

### ISSUE THREAD

**Issue by klabe** [snoplus/orca#86]
Orca wants to use your confidential information stored in "couch.snopl.us [snoplus]" in your keychain.

This message seems to appear when standard run values are fetched from couchdb.  Can we avoid this from popping up all the time?

**Comment by tlatorre-uchicago** [comment]
Possibly related to #132.

**Comment by tlatorre-uchicago** [comment]
I haven't seen this in a while, so I'm going to close it.
