### ISSUE TITLE
PGT/PED pulser feed selection changed by ORCA

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#91]
As seen and described in detail in this shift report:
http://snopl.us/shift/view/fb16909f4f4248b5a3fb0e2ce4a19ce1

**Comment by jcaravaca** [comment]
The PED mode is set when in an 'ECA' standard run and PGT otherwise. This is fixed by #75 where the state of the button is saved in the StandardRun DB

**Comment by fbdescamps** [comment]
OK, but they did not change the run, it was marked maintenance, default as far as I remember.

**Comment by jcaravaca** [comment]
It was called 'MAINTENANCE' and hence it will switch to PGT as it wasn't the 'ECA' standard run. We tested it this afternoon and that's what was happening.

**Comment by fbdescamps** [comment]
understood, thanks!
