### ISSUE TITLE
Update GT and ped crate mask GUI 

### ISSUE THREAD

**Issue by marzece** [snoplus/orca#96]
We should replace some of those "spares" with more appropriate titles

**Comment by tlatorre-uchicago** [comment]
@marzece Are you going to update this as part of the new MTC GUI work you're doing?

**Comment by marzece** [comment]
I can, yeah.

**Comment by fbdescamps** [comment]
Maybe move TUB to a different bit so that we can have crate 19?

**Comment by marzece** [comment]
Done in #274. There's still spares but now they're actually unused spares.
