### ISSUE TITLE
Unable to enter > 1000sec for run length in the Run Control panel

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#98]
When trying to set the run length for example to  3600sec, ORCA changes the length to 3secs. Weirdly ORCA makes it into ```3,600``` then to ```3``` when hitting enter. It seems to take any number before the comma for numbers larger than 999. This does work in the SNO+ Control Panel.

**Comment by marzece** [comment]
#89...this is awkward

**Comment by cjones2500** [comment]
Hi Freija,

This is a setting in the textbox that you can auto-force validation. Check that one of its properties is not autovalidating. It will also use the value that is forced. That could be the problem.




On 9 May 2016, at 07:43, Freija Descamps <notifications@github.com<mailto:notifications@github.com>> wrote:


When trying to set the run length for example to 3600sec, ORCA changes the length to 3secs. Weirdly ORCA makes it into 3,600 then to 3 when hitting enter. It seems to take any number before the comma for numbers larger than 999. This does work in the SNO+ Control Panel.

**Comment by fbdescamps** [comment]
Apparently a duplicate issue, hmm, it was late! :)

**Comment by fbdescamps** [comment]
Already reported in #89, closing.
